channels:
    - conda-forge
    - tallic
dependencies:
    - python=3.7
    - pip=20.3.3
    - pip:
      - numpy==1.19.2
      - pandas==1.1.4
      - setuptools==50.3.2
      - sagemaker==2.35.0
      - statsmodels
      - fsspec==0.7.4
      - scipy==1.5.4
      - sagemaker[local]


